### ISSUE TITLE
TS2 crashes apon creating route over switches

### ISSUE THREAD

**Issue by melbournefan** [ts2/ts2#115]
I'm creating a route in TS2 which involves a set of points to crossover to another track however when I try and set a 'route' in the routes tab TS2 crashes and the debug window suggests that the switch isn't somehow linked properly even though when I've clicked on the validation button no dialogs have appeared.

Set of points I'm trying to setup
![image](https://user-images.githubusercontent.com/41057813/151914433-0c331597-9bc4-4234-ba78-8e0eda9a428a.png)
Debug window
![image](https://user-images.githubusercontent.com/41057813/151914497-0be43138-2396-4901-99ce-9b0879615d5b.png)

Thanks

**Comment by npiganeau** [comment]
Hello @melbournefan,

Can you attach your simulation so that I can have a look ?

**Comment by melbournefan** [comment]
Sure, had to zip it because  .ts2 wasn't a valid file format on GitHub
[UFD - Copy.zip](https://github.com/ts2/ts2/files/7977226/UFD.-.Copy.zip)

**Comment by npiganeau** [comment]
![image](https://user-images.githubusercontent.com/3935559/152129523-732914e9-dfd2-409e-ac8b-1c4a0f43014a.png)

It's because the crossover track is connected to the top right end of the top points instead of the bottom left end. Same pb for the bottom points. It should be like this:

![image](https://user-images.githubusercontent.com/3935559/152129985-eaecb617-731d-4e72-b15c-05dd773f8acd.png)

And you also have an issue with the main track bottom left : 

![image](https://user-images.githubusercontent.com/3935559/152130098-ae2938d4-d600-4d1a-b179-13cb51cc664c.png)

It should be like this :

![image](https://user-images.githubusercontent.com/3935559/152130239-38333ae4-db4c-4732-a33f-a6d4bd45a7b3.png)

If I remove the points to have a better look, it's like this:

![image](https://user-images.githubusercontent.com/3935559/152130365-b95873c4-54fe-4414-8ec5-a74570894dec.png)

Hope it helps.

**Comment by melbournefan** [comment]
Yep that worked, thanks for that
