### ISSUE TITLE
advice wanted

### ISSUE THREAD

**Issue by pedromorgan** [ts2/ts2#30]
@npiganeau

come comments helpful as am hacking away.. and json serialize

Does this for ti_type look right ?
```
        class TI:
            place = "A" #?
            line = "L"
            platform = "LP"
            invisible_link = "LI"
            signal = "S"
            signal_bumper = "SB"
            signal_timer = "ST"
            non_return = "SN"
            text = "ZT"
```

**Comment by npiganeau** [comment]
TrackItems logic has changed in the develop branch compared to the master branch, so I suggest you work on the json serialization on the develop branch rather than the master branch.

The mapping in the develop branch is the following (see simulation.createAllTrackItems() or editor.editor.createTrackItem():

    "L": LineItem
    "LI": InvisibleLinkItem
    "S": SignalItem
    "P": PointsItem
    "E": EndItem
    "A": Place
    "ZT": TextItem
    "ZP": PlatformItem

- "LI" because InvisibleLinkItem is a subclass of LineItem "L"
- Place are "A" simply because "P" was taken by points before...
- Items starting with "Z" are props that are not needed for the simulation to work, but just to have pleasant graphics for the user.
- Old "SB", "SN" and "ST" are now implemented as "S" with special parameters.

**Comment by pedromorgan** [comment]
umm..
This is chicken and egg situation as I am based on Qt5 branch (not PyQt4)..

Is a merge of develop into Qt5 gonna mess up.. pete thinks....

**Comment by pedromorgan** [comment]
Added the controls and stuff to a new toolbar
![ts2_toolbar](https://cloud.githubusercontent.com/assets/123932/8016517/32b1f61a-0bdc-11e5-8e05-7c77ae1de449.jpeg)

**Comment by pedromorgan** [comment]
No feedback ;-(

**Comment by npiganeau** [comment]
This is great ! It enables the user to move the tool bars around to make his screen looks as he wants.

Just push it on the develop branch

**Comment by pedromorgan** [comment]
umm.. maybe I create a "topic/toolbar" branch first.. cos its a bit tricky to "restore"..
and kinda wanna nail the dual screen scenariio also... ie can we make it work on 2 screens.. ?? thnks aloud

**Comment by npiganeau** [comment]
It should be possible since Qt has classes to manage several monitors, but I never tried it.

That would be a cool feature if we manage to separate layout on one screen and data on the other screen for example. Or maybe the layout on top across both screens and data below. Or whatever...

I first developed ts2 on a 1920px screen and it was cool, but now I only have 1366px and it's quite impossible to play actually ! So managing several screens is a good idea

**Comment by pedromorgan** [comment]
Same problem here... so maybe ts2 is the guinea pig ;-))))))))))
