### ISSUE TITLE
[Suggestion] Repository clean-up request

### ISSUE THREAD

**Issue by mcgiwer** [ts2/ts2#45]
Hello. I wanted to suggest that you guys do a clean-up in the ts2 repository because it's one big mess right now with too many splits and the code of PyQt4, PyQt5 mixed up in one place.

My suggestion is to:

* message about the repo maintanance with request to hold up with works
* save the repo deplay key (if there is any)
* clean-up the code (leave only the latest PyQt5 development and latest stable version) by remove anything else (all remaining code and branches then the latest ones

After the maintanance is done, inform the contributors that they can pull the fresh version

**Comment by pedromorgan** [comment]
We're all trying to and working towards that..
Indeed its a big change atmo, and I aint got time, and kinda  newbie like u.. ;-(

But just over the horizon is... in "develop branch"

Ie .. new release == 
- PyQt5 - and this means we can then exise all pyqt4 code et all
- Also json for data storage instead of sqlite... so removes a dependancy
- and lots of change in sim code..

Unfortunately.. I only got time to help @npiganeau atmo as he's the main coder..

So I can only really focus on the fringe such as website etc as we prepare.. osassionally

And its involved with 
a new website and homepage here (can u help)
http://ts2.github.io/

also were splitting the data in a new repos here..
https://github.com/ts2/ts2-data

and we need screenshots if u can help..
https://github.com/ts2/ts2-screenshots

And the developer docs are outta data,, might fix tonite but at
http://docs-ts2.rhcloud.com/

and idea is to "share sims".. etc

Its fantastic @mcgiwer .. Lets move on.. ;-)))))))))))))

What can u help with ?
which os, skills, langs.. et all :-)))))

**Comment by pedromorgan** [comment]
Actually @mcgiwer you made me think of another idea.. really.. but..

We could just rename this repos as ts2-legacy
Then `create` a NEW  pyqt5 - develop ts2 repos.. 
with all olde crap gone ie sqlite, pyqt4 et all.. a new start..
and maybe bump a version to `15` or something easier than current
It would be up to @npiganeau really if we "loose history".. 
but the pain of use starting with a new clone would be much much smaller.. 
particulat because of binary blobs etc..

Thinking aloud..

**Comment by Sharpe49** [comment]
I don't think creating a new repository is useful.
The current size of my working directory is 8,81 MB.
That's very small. Let's compare this with Open Rails history which was full of compiled programs till one or two years ago : 743 MB when cloned with git-svn.

Also, I don't think doing a huge version bump is useful either. But we can apply the semantic versioning method which is the one that is used in most open source projects : http://semver.org

**Comment by npiganeau** [comment]
The github repo is a source repo. Its aim is to manage sources and trace development history for hackers. 

It is not meant to be a deployment repository. Currently deployment is made from the 'releases' tab of this repo or from sourceforge.net. Although there are plans for it (#38), there is no continuous integration yet.

Current released version is 0.5, and it is PyQt4 only. It is certainly a pity, but it's due to the fact that most of the current release code has been made two years ago at a time where riverbanks did not ship python3+PyQt5 windows binaries, and windows releases have always been my priority due to the number of potential users on this platform.

Now, it is the contrary, we only have python3+qt5 on windows and most of linux distributions, so we stepped to this in v0.6, but v0.6 is not released yet. Hackers and bold users can checkout develop branch if they want to see it, but it is still WIP.

I will not change repo each time I make a change, knowing that changing from pyqt4 to pyqt5 is actually a 'small' change compared to other changes in the software (just count the number of commits/line changed). As pointed above by @Sharpe49 , this is still beta software and you should expect incompatibilities between versions.
