### ISSUE TITLE
[Idea] Programming language change idea

### ISSUE THREAD

**Issue by mdziczkowski** [ts2/ts2#57]
hey @npiganeau I hust had a interesting idea. Have you heard about the GO language? it's kinda easy to learn and gives less problems then pyqt, besides it work easyly with json, with would correspond quite good with the webserver idea you work at. I think the result of testing it could be very interesting

**Comment by pedromorgan** [comment]
I use golang on some web projects, and indeed its cool and nice and love it.

However, it has not got a mature gui api; and the current qt bindings are for qml only, so its not really a contender.

**Comment by mcgiwer** [comment]
@pedromorgan I thought more about it as the part of the webserver part of the project

**Comment by pedromorgan** [comment]
I considered it for the server, which I started an idea here https://github.com/ts2/ts2-server,

But then considered that ts2 is in python, so we might as well make server python.. It could still be done in golang though.

**Comment by pedromorgan** [comment]
@mcgiwer Can u code in go ?

**Comment by mcgiwer** [comment]
@pedromorgan I just started to learn it

**Comment by pedromorgan** [comment]
That's great, its a real fun language :+1:

**Comment by Sharpe49** [comment]
For the moment, this language is used by a minority. I don't think we should use it.
Having a good language isn't the most important thing in software development.
The most important thing is having great libraries.
And the best languages for this are C/C++, C#, Java and Python (we can also add PHP in this list, but it is more webpages oriented).
The problem with Python is that, for applications that are very CPU intensive (such as servers for example), it is really slow. A compiled program will always be better in this case.
For me, if we had to change the language of the program, it wouldn't be for Go but for C/C++ or C#.

**Comment by pedromorgan** [comment]
@mcgiwer  created a new repos.. lets have fun ;-)

@Sharpe49 its not c++ .. NOTED the guys behind go is Rob Pike and God himself and Not Dennis.. 

Re your problems.. re php which is executed on each page ht and aspx, which like python run in a virtual machine, vs a c++ and hardcore wbser is definatelly something u understand.. and how it works..

So for fun, can we entertain all is what we want.. We need and API into ts2..
so all of us in different langs et all, can play with it.. etc etc..

In my eyes ts2 is a signalling simulation. and if it were real then my ardiono would be out.. etc..

I see "Ts2 Signalling" to control my set, and the "simulation part" is fun maybe. .is another way to think about..

How far do we want to go.. ?? can u code? or more important @Sharpe49  give advice and some doces etc and link.. This is a baby project, and needs a night nurse.. ;-)

**Comment by Sharpe49** [comment]
By the way, yes I can code in C/C++ (I used it at work in order to create a Qt program), C# (I am a developer of Open Rails), Ada (also at work since I am a signalling engineer and Ada is the most used language for secure systems), PHP (I have several small websites).

**Comment by pedromorgan** [comment]
Interesting..
So ts2 was original in qt/c++
and rail not familiar, but grew up with php then python.. and at 50+
Also php developer of smarty in yoonder years.. 

Whats Ada ?

How do I run c# on my linux box?

**Comment by pedromorgan** [comment]
OOPs ok so read up on ADA..

Thats why we want to use golang, cos there's no headers, compiles fast and throws a tantrum sometimed..

Re writing a server in c or c++, I am still trying to wan flightgear off that concept..

Can u please help, but nagging more please ;-)))
I like to get to root cause, and if a guy codes in php, then I kinda wanna help her/him only more tangents ...

**Comment by Sharpe49** [comment]
Ada is a special programming language since it is very strict, which is why it is appreciated for secure systems.
For example, the typing : if you create an alias to Integer (let's call it Distance)... you cannot add a Distance with an Integer. You can only add another Distance variable.

For C#, you can use it with the Mono framework on Windows, Linux and Mac.
For compiled CLR/MSIL executables, you can also execute them with the Mono framework.
Open Rails (the MSTS compatible train simulator) is using C#. It's not currently compatible with Linux due to its dependencies (XNA framework). I am trying to get them to use OpenTK (= OpenGL) but it's difficult to convince them.

By the way, with Qt, you can create servers easily with the Qt Network module.

**Comment by pedromorgan** [comment]
irc.freenode.net#trainsigsim ;-)

**Comment by pedromorgan** [comment]
re ada: is this for embedded system ?? or a general PC ?? i assume u cant run ada on a PC cos it need full control..

I dont wanna write a c++ application for ts2.. yet.. so maybe we need to decide what the funcionality is first.. ;-)

**Comment by pedromorgan** [comment]
@mcgiwer @Sharpe49 @npiganeau  
Created a ts2-go repos.. lets have funs...

If anyone wants ts2-rb or other langs.. then please lets move forward.. ;-)

**Comment by pedromorgan** [comment]
@mcgiwer https://github.com/ts2/ts2-go

**Comment by mcgiwer** [comment]
I have proposed GO for the server because it's less resource intense then other languages like @Sharpe49 has good noticed

**Comment by pedromorgan** [comment]
https://github.com/ts2/ts2-go

And rob pike
- parellel is not concurrent
- explain that to set of railway guys..
- ;-))) 
- Not multi threaded is it ?

**Comment by pedromorgan** [comment]
@mdziczkowski dreams do come true..  maybe.. ;-)

https://github.com/ts2/ts2-sim-server
