### ISSUE TITLE
HELP

### ISSUE THREAD

**Issue by pedromorgan** [ts2/ts2#72]
So yhis is an issude to eveyone who read this..

The baciscs are..
maind line to singals
So if it crashes and no services are running, eg Winter
Then I can go gome and not worrt about it for a few days

- we need acceleration
- and go bigger

I want to put it here
-how I epecrt the works.. to go..
If I click the buton

We need nobble need to on fringe()
= @mcgiwer  The little devil..

**Comment by mcgiwer** [comment]
I have converted the JSON files to go structures. I had some issues with the "TrackItems" because they were too much mixed up and I needed to split them to several structures, however the structures are universal and can be used to the track JSON data.

The code can pe previewed on https://gitlab.com/mcgiwer/ts2-go/tree/master

I tryed to upload it on github but some kind of error prevented me from that

**Comment by pedromorgan** [comment]
See https://github.com/ts2/ts2-go for more @mcgiwer
