### ISSUE TITLE
v0.7 ROADMAP

### ISSUE THREAD

**Issue by pedromorgan** [ts2/ts2#76]
@npiganeau Now that the develop branch is "naked"..

Is there anycode available to work on. ??

Or is it a start from scratch ???

What do u want help with ?

**Comment by pedromorgan** [comment]
https://github.com/ts2/ts2/wiki/New-Arch

**Comment by npiganeau** [comment]
@pedromorgan The things to do in order are, IMO:

1. Create the sim server according to https://github.com/ts2/ts2/wiki/TS2-Sim-Server-Specifications up to step 2.
  - I have started some trials in go that I've pushed on the nextarch branch
  - Options loading is OK but is not able to load v0.6 string options. I think we should change v0.6 to generate typed JSON options instead of string.
  - I played around for some time before finding how to implement trackItems. I think that it's good now.
  - The rest (Services, Trains, etc.) is to be done. I think that simple struct should be enough for them.

2. When we have a step 2 sim-server then we can start adapting v0.6 to become the PyQt client of v0.7

3. In the meantime, we will update the sim server to step 3 and 4 + create the managers (in go or python, we'll see)

**Comment by pedromorgan** [comment]
Playing here.. for fun https://github.com/ts2/ts2-sim-server

and researching Signals.. and
find this something I didnt realise there..
https://github.com/ts2/ts2/wiki/Signal-Library

So look at that and then this
https://github.com/ts2/ts2/blob/master/ts2/scenery/signals/signalitem.py#L35

And am trying to figure it out, both in a kinda 'real signal'
and danger, caution, proceed, double yellow etc..
Whats comfusing me is the state is missing.. or am I missing something..

Also can u point to where u stack these lights on top or side by side of each other.. structure I dont get atmo.. or am missing something,.. or stupid... probably last

**Comment by pedromorgan** [comment]
umm
https://github.com/ts2/ts2-data/blob/master/UK/signals/UK.tsl
vs
http://www.railway-technical.com/sig-uktypes.shtml#Colour-Light-Signals

So that UK right..
aspect = color..

**Comment by npiganeau** [comment]
Aspect in ts2 = aspect as defined in [SimSig's glossary](http://www.simsig.co.uk/dokuwiki/doku.php?id=usertrack:glossary:aspect) , that is : 
1. A colour of a signal lamp or combination of lamps (defined by all the JSON fields of ```signalAspect```, except the ```actions``` field) 
2. A message to the drivers (the ```actions``` to perform)

A ```state``` is an abstraction, it does not match to a real thing. It is an aspect and a set of conditions for this aspect to show: e.g. 

```Sample state = "we show green (Aspect) if a route is set (Condition 1) and there is not train in next block (Condition 2) and next signal is not red (Condition 3)."```

 The ```state``` is put on a stack: the ```states``` of the signal type, which is evaluated in order to define the aspect to show during the simulation. The first state with all its conditions filled is selected and its aspect shown.

Thus, we have at least one state for each aspect that this signal might show, but there can be the same aspect in several states at different levels of the stack. If we take "3 aspect signal" in UK.tsl, it is also an approach control from red when you have a diverging route set, so the red aspect appears twice in the stack (first and last states):

1. We check if we have the diverging route set, and no train approaching =&gt; we show the red aspect
2. If not we check if the signal should be green (a route is set from this signal, there is no train in the block and the next signal is green, yellow or double yellow)
3. If not we check if the signal should be yellow (a route is set from this signal, there is no train in the block and the next signal is red (with or without aux signal) or buffer)
3. If not we show the red aspect

SignalLibrary is built by combining data from the builtin inside signalitem.py + tsl files (the latter overwrite the former if they define the same fields).

**Comment by pedromorgan** [comment]
Thankyou, things are clearer.. (might stick above in the wiki..)

**Comment by npiganeau** [comment]
Yes, please do update the wiki to make things clearer.

Forgot also to tell that the lamps are defined like this:
```
    ||
6 5 ||
4 3 ||
2 1 ||
  \-||
    ||
```
Since switched off lamps are not shown, same aspect can be used in different signal types (e.g. red from 3 aspect or 4 aspect signals is the same aspect in ts2)

**Comment by pedromorgan** [comment]
um.. or reverse..ed

But me need to be back as the "hitch-hickers-guide".. for a complete muppet
to start..
like me..

**Comment by pedromorgan** [comment]
https://github.com/ts2/ts2/wiki/Developers-TODO

**Comment by pedromorgan** [comment]
@npiganeau Can u (if u got time).. just make up the simple websocket that sends the clock...  every few seconds or so..

Hidden agenda is that I need ws in a RL app, and pyqt3, so can experiment

**Comment by npiganeau** [comment]
@pedromorgan work is slow but ongoing... The simulation's clock is now ticking but now I need to make the interface between the simulation and the server's hub and then to define a registry in the hub to keep track of which connection follows which event (+ define subscription system like flight gear addListener). Then I will be able to send the ticks to the subscribed connections.

Almost there !

**Comment by mcgiwer** [comment]
don't forget to number (and make the numbering visible) of each track that there won't be any issues in directing trains on propper tracks. In previous version this was missing and it made the simulation bit harder to use

**Comment by npiganeau** [comment]
@pedromorgan Clock ticks ! Check https://github.com/ts2/ts2/wiki/TS2-Websocket-Protocol to get how to add the "clock" listener and start/pause the simulation.

**Comment by pedromorgan** [comment]
@npiganeau Can i add a few comments... just to be a pain in the ass ;-))) (sorry in advance)

# object = Simulation, Server 
I notice the capital S..... in code also... and i kinda would prefer lower case or indeed case insensitive... I also respect that things are a bit confusing with the origiinal `caseType` vs go's `CaseType`.. sigh!

# Login = Register
I kinda think login is the wrong terminology and suggest Register..

If its gonna end up online later, then we add Login implemntation but for now I think its all local on Lan..(or your kids hacking - learning from dadi)

The register token,  could be more than one, and the thought here is of a few "arduino powered signals" or an android.. and the need to register each "interface" via its token...but idea for future.

# Rename
`MessageType` could be `MsgType`
(I do miss MsgType.RESPONSE in go.. ye class constants as in c++ and python)

I kind understand the KO terminology.. is that "common"... ??  but a cool one to have staring at screen as a wtf with one type0,  could this not be success/fail instead and a message accepted regardless eg
```
data : {status: "OK", message: "its working on status bar"}
data : {status: "FAIL", message: "it failed for xyz working"}
```
