### ISSUE TITLE
API?

### ISSUE THREAD

**Issue by gondilon** [ts2/ts2#87]
I was digging through the source code files and I found a folder labeled API with some almost empty files in it. Is there a functional API, and if so are there instruction on how to use it?

**Comment by npiganeau** [comment]
Hi, thanks for your interest in ts2.

No, we do not have an API to access ts2 from outside. The API folder in the docs is there to generate documentation on the source code for people who want to hack ts2 from inside.

Though we do have plans in an undetermined future to rework completely ts2 architecture so that it will work with independent processes communicating through websockets (see https://github.com/ts2/ts2/wiki/New-Arch) so that each component could be replaced (e.g. to connect to a real model train through Arduino or such). See also https://github.com/ts2/ts2-sim-server for "ongoing" (stalled actually :-( ) work on the subject.

**Comment by gondilon** [comment]
Are there instructions somewhere on how to generate said documentation?

**Comment by gondilon** [comment]
Also I am interested in using the TS2 simulator as a data source for a  project to build a new type of train dispatcher interface. What is the best way to communicate with you directly about said project?

**Comment by npiganeau** [comment]
Doc is to be generated by sphinx (see http://www.sphinx-doc.org/en/stable/tutorial.html). 

Not sure about what to do exactly, as it was done by @pedromorgan, but probably something with `sphinx-build`

**Comment by npiganeau** [comment]
Can you tell us more about your new type of train dispatcher interface? How do you intend to code it?

**Comment by gondilon** [comment]
I would prefer not to discuss that on this public site. What I can tell you is that we are looking for a train dispatching simulator to be the "under the hood" part of our new dispatcher interface, and we think that the TS2 would be a good fit. We are applying for a grant to fund the development costs of this new interface, so we could include the cost of modifying the TS2 system in that proposal. Connect with me on LinkedIn [https://www.linkedin.com/in/carlmacystanton/](url) or twitter [https://twitter.com/CarlMacyStanton](url) and we can talk in more detail.

**Comment by pedromorgan** [comment]
Closed by pedro. for ts2-sim-server

**Comment by pedromorgan** [comment]
But we need the schema, and work unserway
