### ISSUE TITLE
Editor doesn't load the map (probably too many elements)

### ISSUE THREAD

**Issue by Sharpe49** [ts2/ts2#96]
The following file was saved from the editor this morning. It does not seem corrupted but the editor does not show the map after loading.
[paris-montparnasse.zip](https://github.com/ts2/ts2/files/3747056/paris-montparnasse.zip)
The errors (Item not linked) during loading are expected to happen since I have not finished the map so I can't validate it.

Does this file work on your side ? If not, do you have an idea why this doesn't work anymore ?

Thank you.

**Comment by npiganeau** [comment]
Are you sure you have the latest version of TS2? This is an issue I had in a previous version, I thought I fixed it.

Actually your simulation loads fine, but you need to scroll full bottom right to see it. This is because you have a single item at the full top right which is lost there. I've seen this when moving an item it became weird and went the wrong way.

Just scroll full top left, delete the item, save and reload and it should be fine. See corrected attached simulation: [paris-montparnasse.zip](https://github.com/ts2/ts2/files/3764125/paris-montparnasse.zip)

Looking forward to seeing this simulation finished !

**Comment by Sharpe49** [comment]
Ok... that was weird.
The coordinates of this element were really weird.

Ok, so no issue then ! :)
